all:
  hosts:
    server01:
      ansible_host: 10.1.1.10
      nr_environment: prod
      nr_institution: payments
      os_family: linux

    server02:
      ansible_host: 10.1.1.11
      nr_environment: nprod
      nr_institution: payments
      os_family: linux
