all:
  hosts:
    server01:
      ansible_host: 10.1.1.10
      nr_environment: dev
      nr_institution: CU

    server02:
      ansible_host: 10.1.1.11
      nr_environment: qa
      nr_institution: RUSM
