---

- name: Validate nr_version
  fail:
    msg: "nr_version not provided"
  when: nr_version is not defined

- name: Validate application_type
  fail:
    msg: "Unsupported application_type"
  when:
    - application_type is not defined
    - application_type | lower not in ['standard','prosam','ssb9']

- name: Validate application_name
  fail:
    msg: "application_name not provided"
  when: application_name is not defined

- name: Normalize variables
  set_fact:
    env_tag: "{{ input_tag_Environment | lower }}"
    inst_tag: "{{ input_tag_institution }}"
    app_name: "{{ application_name }}"

- name: Select license key
  set_fact:
    newrelic_license_key: >-
      {{
      lookup('env','NEW_RELIC_LICENSE_KEY_PROD')
      if env_tag=='prd'
      else
      lookup('env','NEW_RELIC_LICENSE_KEY_NPROD')
      }}
