---
- name: Normalize tags
  set_fact:
    env_tag: "{{ input_tag_Environment | default('Unknown') | lower }}"
    inst_tag: "{{ input_tag_institution | default('Unknown') }}"

- name: Select license key
  set_fact:
    newrelic_license_key: >-
      {{
        lookup('env', 'NEW_RELIC_LICENSE_KEY_PROD')
        if env_tag == 'prd'
        else
        lookup('env', 'NEW_RELIC_LICENSE_KEY_NPROD')
      }}

- name: Ensure unzip is installed
  package:
    name: unzip
    state: present

- name: Download New Relic Java agent 
  get_url:
    url: https://download.newrelic.com/newrelic/java-agent/newrelic-agent/8.21.0/newrelic-java-8.21.0.zip
    dest: /opt/newrelic-java.zip
    mode: '0644'

- name: Extract New Relic agent
  unarchive:
    src: /opt/newrelic-java.zip
    dest: /opt
    remote_src: yes
    creates: "/opt/newrelic/newrelic.jar"

- name: Replace license key in newrelic.yml
  replace:
    path: /opt/newrelic/newrelic.yml
    regexp: "<%= license_key %>"
    replace: "{{ newrelic_license_key }}"
  notify: restart sigma services  

- name: Check installed New Relic agent version
  shell: unzip -p /opt/newrelic/newrelic.jar META-INF/MANIFEST.MF | grep Implementation-Version
  register: newrelic_version
  changed_when: false

- name: Show installed agent version
  debug:
    msg: "Installed New Relic Java Agent Version: {{ newrelic_version.stdout }}"
