---
- name: Validate New Relic version input
  fail:
    msg: "nr_version not provided"
  when: nr_version is not defined
  
- name: Normalize tags
  set_fact:
    env_tag: "{{ input_tag_Environment | default('unknown') | lower }}"
    inst_tag: "{{ input_tag_institution | default('unknown') }}"
    app_name: "{{ input_app_name | default('unknown') }}"

- name: Select license key
  set_fact:
    newrelic_license_key: "{{ lookup('env', 'NEW_RELIC_LICENSE_KEY_PROD') if env_tag == 'prd' else lookup('env', 'NEW_RELIC_LICENSE_KEY_NPROD') }}"

- name: Check if New Relic agent exists
  ansible.builtin.stat:                           # Helps to Retrieve file or file system status
    path: /opt/newrelic/newrelic.jar
  register: nr_agent

- name: Get installed version
  shell: unzip -p /opt/newrelic/newrelic.jar META-INF/MANIFEST.MF | grep '^Implementation-Version'  # version check command
  register: current_version
  failed_when: false                              # Error Handlings , we can define the failures
  changed_when: false                             # Error Handlings , REports change and triggers Ansible handlers
  when: nr_agent.stat.exists

- name: Determine upgrade requirement
  set_fact:                                       # condition: upgrade? not true or current version != nr_version
    upgrade_required: "{{ (not nr_agent.stat.exists) or (current_version.stdout is not search(nr_version)) }}"

- name: Install or upgrade New Relic agent
  block:

    - name: Download New Relic agent
      get_url:
        url: "https://download.newrelic.com/newrelic/java-agent/newrelic-agent/{{ nr_version }}/newrelic-java-{{ nr_version }}.zip"
        dest: "/opt/newrelic-java.zip"
        mode: '0644'
        force: yes                                #forcing the replace the file because it's already exist and not allow to download latest agent file.
                                                  #{Because of same file name and to avoid 304 Not modified error}

    - name: Remove existing New Relic agent
      file:
        path: /opt/newrelic
        state: absent

    - name: Extract New Relic agent
      unarchive:
        src: "/opt/newrelic-java.zip"
        dest: /opt
        remote_src: yes

    - name: Update license key
      lineinfile:
        path: /opt/newrelic/newrelic.yml
        regexp: '^\s*license_key:'
        line: "  license_key: {{ newrelic_license_key }}"

    - name: Update app name
      lineinfile:
        path: /opt/newrelic/newrelic.yml
        regexp: '^\s*app_name:'
        line: "  app_name: {{ app_name }}"
        firstmatch: yes

    - name: Restart Tomcat
      ansible.builtin.shell: |
        /opt/tomcat/bin/shutdown.sh || true
        sleep 5
        /opt/tomcat/bin/shutdown.sh || true
        sleep 10
        /opt/tomcat/bin/startup.sh
      args:
        executable: /bin/bash

  when: upgrade_required
