- name: Ensure unzip installed
  package:
    name: unzip
    state: present

- name: Create installation directory
  file:
    path: "{{ newrelic_agent_dir }}"
    state: directory
    mode: '0755'

- name: Download New Relic Java agent
  get_url:
    url: "{{ newrelic_zip_url }}"
    dest: "{{ newrelic_install_dir }}/{{ newrelic_zip_file }}"
    mode: '0644'

- name: Unarchive agent
  unarchive:
    src: "{{ newrelic_install_dir }}/{{ newrelic_zip_file }}"
    dest: "{{ newrelic_install_dir }}"
    remote_src: yes
    creates: "{{ newrelic_agent_dir }}/newrelic.jar"

- name: Determine license key
  set_fact:
    newrelic_license_key: >-
      {{
        lookup('env', 'NEW_RELIC_LICENSE_KEY_PROD')
        if env_effective == 'prd'
        else
        lookup('env', 'NEW_RELIC_LICENSE_KEY_NPROD')
      }}

- name: Configure newrelic.yml
  template:
    src: newrelic.yml.j2
    dest: "{{ newrelic_config }}"
    mode: '0644'
