application_configs:

  standard:
    tomcat_path: /opt/tomcat
    setenv_template: setenv.sh.j2
    restart_handler: restart standard tomcat

  ProSAM:
    tomcat_path: /sigma/tomcat
    setenv_template: setenv_prosam.sh.j2
    restart_handler: restart prosam services
    service_user: sigqa

  SSB9:
    tomcat_path: /u01/tomcat/8100
    setenv_template: setenv_ssb9.sh.j2
    restart_handler: restart ssb9 services
    service_user: sigqa
