---
- name: restart standard tomcat
  shell: |
    /opt/tomcat/bin/shutdown.sh || true
    sleep 10
    /opt/tomcat/bin/startup.sh
  args:
    executable: /bin/bash

- name: restart prosam services
  become_user: sigqa
  become: sudo
  shell: |
    /sigma/tomcat/bin/catalina.sh stop || true

    /sigma/qa/bin/ixsqps_stop || true
    /sigma/qa/bin/ssiapix_stop || true

    sleep 5

    /sigma/qa/bin/ssiapix_start
    /sigma/qa/bin/ixsqps_start

    /sigma/tomcat/bin/catalina.sh start
  args:
    executable: /bin/bash

- name: restart ssb9 services
  become: true
  become_user: sigqa
  shell: |
    /u01/tomcat/scripts/stop_ssb9.sh || true
    sleep 10
    /u01/tomcat/scripts/start_ssb9.sh     
  args:
    executable: /bin/bash  
